# This config file defines configurators to be used for other services

parameters:

    app.bundle.config.user.class: AppBundle\Configurator\UserConfigurator

services:

    # This injects the User object from the security.context
    app.bundle.config.user:
        class: %app.bundle.config.user.class%
        arguments: [@security.context]
