# Define only helpers or helper related services here

parameters:

    app.bundle.helper_bag.class:             AppBundle\Helper\HelperBag
    app.bundle.helper.flash.class:           AppBundle\Helper\FlashHelper
    app.bundle.helper.user.class:            AppBundle\Helper\UserHelper
    app.bundle.twig.extension.helper.class:  AppBundle\Twig\Extension\HelperExtension

services:

    # This is the template for making controller and view helper bags
    app.bundle.helper.helper_bag:
        class: %app.bundle.helper_bag.class%
        public: false

    app.bundle.helper.flash:
        class: %app.bundle.helper.flash.class%
        arguments: [@session]
        tags:
            - { name: helper.controller, alias: flash }
            - { name: helper.view, alias: flash }

    app.bundle.helper.user:
        class: %app.bundle.helper.user.class%
        configurator: [@app.bundle.config.user, configure]
        tags:
            - { name: helper.controller }
            - { name: helper.view }

    app.bundle.twig.extension.helpers:
        class: %app.bundle.twig.extension.helper.class%
        tags:
            - { name: twig.extension }

