# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.bundle.controller.helpers:
        class: AppBundle\Controller\Helpers\Helper

    app.bundle.controller.helper.flash:
        class: AppBundle\Controller\Helpers\FlashHelper
        arguments: [@session]
        tags:
            - { name: controller.helper, alias: flash }
